- name: Installing sudo
  become: true
  pacman:
    state: present
    name:
      - sudo

# from: https://github.com/kewlfft/ansible-aur/blob/master/README.md
- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
    shell: /bin/bash

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
    mode: '0644'
