---
# Disabled since there is currently no need for this, and it causes issues with
# the way podman currently runs the infra container. Not removed because this
# is needed if/when we try to resurrect DNS-based filtering.
# - name: Ensure custom resolv.conf
#   become: true
#   ansible.builtin.copy:
#     src: resolv.conf
#     dest: /etc/resolv.conf
#     mode: 0744

- name: Update pacman cache
  pacman:
    update_cache: true
    upgrade: false
  changed_when: false

- name: Installing base packages
  become: true
  pacman:
    state: present
    name:
      - vim
      - dhcpcd
      - python
      - python-netifaces
      - tmux
      - tmuxp

- name: Enable timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true

- name: disable the first-boot service
  become: true
  ansible.builtin.systemd:
    name: systemd-firstboot.service
    masked: true

- name: Installing sysctl config
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/sysctl.d/{{ item }}"
    mode: 0644
  loop:
    - 10-printk.conf
    - 10-disable-ipv6.conf

- name: creating dir for app-specific config
  become: true
  ansible.builtin.file:
    mode: 0744
    path: "{{ app_config }}"
    state: directory
