---
- include_tasks: time.yml

- name: Ensure custom resolv.conf
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0744

- name: Update pacman cache
  become: true
  pacman:
    update_cache: true
    upgrade: false
  changed_when: false

- name: Installing base packages
  become: true
  pacman:
    state: present
    name:
      - vim
      - dhcpcd
      - python
      - python-netifaces
      - tmux
      - tmuxp

# REVIEW: Why is the needed? Umask is 0750 which seems fine as a default
- name: Ensure root directory permissions
  become: true
  ansible.builtin.file:
    mode: 0700
    path: /root
    state: directory

- include_tasks: aur.yml
