---
- name: Ensure custom resolv.conf
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0744

- name: Update pacman cache
  pacman:
    update_cache: true
    upgrade: false
  changed_when: false

- name: Installing base packages
  become: true
  pacman:
    state: present
    name:
      - vim
      - dhcpcd
      - python
      - python-netifaces
      - tmux
      - tmuxp

- name: Enable timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true

- name: disable the first-boot service
  become: true
  ansible.builtin.systemd:
    name: systemd-firstboot.service
    masked: true

- name: Installing sysctl config
  become: true
  ansible.builtin.copy:
    src: 10-printk.conf
    dest: /etc/sysctl.d/10-printk.conf
    mode: 0644
