---
- include_tasks: time.yml

- name: Check the build environment is correct
  assert:
    that:
      - farm_name is defined
      - valvetraces_minio_password is defined
      - gitlab_access_token is defined
      - gitlab_registration_token is defined
    msg: "environment not correctly setup"

- name: Ensure custom resolv.conf
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0744

- name: Set a hostname
  become: true
  ansible.builtin.shell: |
    printf "{{ farm_name }}-gw\n" > /etc/hostname
  changed_when: false


- name: Update pacman cache
  become: true
  pacman:
    update_cache: true
    upgrade: false
  changed_when: false

- name: Installing base packages
  become: true
  pacman:
    state: present
    name:
      - vim
      - dhcpcd
      - python
      - python-netifaces
      - tmux
      - tmuxp

# REVIEW: Why is the needed? Umask is 0750 which seems fine as a default
- name: Ensure root directory permissions
  become: true
  ansible.builtin.file:
    mode: 0700
    path: /root
    state: directory

- include_tasks: aur.yml
