# A note about the paths in this file
# The docker compose running inside *this* container it actually
# running again the host docker, which means any volumes are resolving
# paths on the *host*, not inside this container.
# However, the build context is inside this container, so paths are
# resolved local to the container we're running in.
version: "3.3"
services:
  mars:
    image: registry.freedesktop.org/mupuf/mars
    environment:
      - MARS_HOST=10.42.0.1
      - MARS_DEBUG=True
      - MARS_SECRET_KEY=$MARS_SECRET_KEY
      - MARS_SQLITE_PATH=/mnt/permanent/mars.sqlite3
    ports:
      - "80:80/tcp"
    volumes:
      - /mnt:/mnt
  pdugateway:
    image: registry.freedesktop.org/mupuf/pdu-gateway
    environment:
      PDUGATEWAY_PORT: 8089
      PDUGATEWAY_STATIC_PDUS: '[{"pdu_name": "farm-pdu-1", "model": "cyberpower_pdu41004", "config": {"hostname": "10.42.0.2"}}]'
    network_mode: host
  salad:
    privileged: true
    image: registry.freedesktop.org/mupuf/valve-infra/salad:latest
    environment:
      SALAD_PORT: 8090
    network_mode: host
  boots:
    privileged: true
    network_mode: host
    image: registry.freedesktop.org/chturne/boots
    environment:
      - BOOTS_SERVICE_PORT=8087
      - BOOTS_HTTP_SERVICE_PORT=8088
      - PRIVATE_INTERFACE=$PRIVATE_INTERFACE
      - MARS_HOST=http://10.42.0.1:80
    volumes:
      - ${TMP_MOUNT}/boots:/boots
      - ${TMP_MOUNT}/boots/nfs-roots:/nfs
      - ${TMP_MOUNT}/boots/nfs-roots:/boots/tftp/nfs
      - /lib/modules:/lib/modules
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v13.5.0
    volumes:
      - ${TMP_MOUNT}/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
