version: "3.8"
services:
  dnsmasq:
    build:
      context: ./component-farm
      dockerfile: dnsmasq.dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/dnsmasq.conf:/dnsmasq.conf
      - ./component-farm/tftp/:/tftp/
    network_mode: "host"

    # MISSING: --platform linux/amd64

# TODO: Add the other services
