#!/bin/bash
# -*- mode: shell-script -*-

set -u

# Generate a configuration file based on the default values, or the overriding
# env vars
[ -d ./config/ ] || mkdir ./config/
echo -e "DNS_SERVER=${DNS_SERVER:-10.0.0.6}
TMP_MOUNT=${TMP_MOUNT:-/mnt/tmp}
PERMANENT_MOUNT=${PERMANENT_MOUNT:-/mnt/permanent}
PRIVATE_INTERFACE=${PRIVATE_INTERFACE:-private}
" > ./config/prod.env

cat ./config/private.env >> ./config/prod.env

. ./config/prod.env

D=$(dirname $(readlink -f $0))

jq -r '.[].name' < machines.db | while read hostname ; do 
    echo -n "Checking $hostname..."
    if ping -c1 $hostname &>/dev/null ; then
        echo -n " PINGOK"
    else
        echo -n " BADPING"
    fi

    if ssh -q -n \
           -o UserKnownHostsFile=/dev/null \
           -o StrictHostKeyChecking=no \
           -i $D/containers/farm-runner/ssh/id_ed25519_farmer \
           root@$hostname &>/dev/null ; then
        echo -n " SSHOK"
    else
        echo -n " BADSSH"
    fi
    echo
done
