---
- name: Installing chrony
  become: true
  pacman:
    state: present
    name:
      - chrony

- name: Enable chrony service
  become: true
  ansible.builtin.systemd:
    name: 'chronyd'
    enabled: yes

- name: Adding configuration for Chrony
  become: true
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart chrony'
