---
- name: Installing Wireguard
  become: true
  pacman:
    state: present
    name:
      - wireguard-tools

- name: Installing network_setup script
  become: true
  ansible.builtin.template:
    src: network_setup.j2
    dest: /usr/bin/network_setup
    backup: true
    mode: 0755

- name: Create the /etc/wireguard directory
  ansible.builtin.file: path=/etc/wireguard/ state=directory mode=0755

- name: Set up the wg0 configuration file
  become: true
  ansible.builtin.template:
    src: 'wg0.conf.j2'
    dest: '/etc/wireguard/wg0.conf'
    mode: 0600

- name: Installing wireguard nft rule
  become: true
  ansible.builtin.template:
    src: 10-wg.nft.j2
    dest: /etc/nftables.d/10-wg.nft
    owner: root
    group: root
    mode: 0644
  notify: 'Restart nftables'

- name: Installing network_setup service
  become: true
  ansible.builtin.copy:
    src: network-setup.service
    dest: /etc/systemd/system/network-setup.service
    owner: root
    group: root
    mode: 0644

- name: Installing find_nic script
  become: true
  ansible.builtin.copy:
    src: find_nic
    dest: /usr/bin/find_nic
    owner: root
    group: root
    mode: 0755

- name: Enabling network_setup service
  become: true
  ansible.builtin.systemd:
    name: network-setup
    enabled: true
