---
- name: Installing Wireguard
  become: true
  pacman:
    state: present
    name:
      - wireguard-tools

- name: Create the /etc/wireguard directory
  ansible.builtin.file: path=/etc/wireguard/ state=directory mode=0755

- name: Set up the wg0 configuration file
  become: true
  ansible.builtin.template:
    src: 'wg0.conf.j2'
    dest: '/etc/wireguard/wg0.conf'
    mode: 0644

- name: Installing wireguard nft rule
  become: true
  ansible.builtin.template:
    src: 10-wg.nft.j2
    dest: /etc/nftables.d/10-wg.nft
    owner: root
    group: root
    mode: 0644
  notify: 'Restart nftables'
