---
- name: Installing Wireguard
  become: true
  pacman:
    state: present
    name:
      - wireguard-tools

- name: Set up the wg0 configuration file
  become: true
  ansible.builtin.template:
    src: 'wg0.conf.j2'
    dest: '/etc/wireguard/wg0.conf'
    mode: 0644

- name: Create a script that will generate the wg0 keys
  become: true
  ansible.builtin.template:
    src: 'wg0_key_gen.sh.j2'
    dest: "{{ wg0_key_gen }}"
    mode: 0755
  notify: "Restart Wireguard"

- name: Create the wireguard keygen service
  become: true
  ansible.builtin.template:
    src: 'wg0_keys.service.j2'
    dest: "/etc/systemd/system/wg0_keys.service"
    mode: 0644

- name: Create the /etc/systemd/system/wg-quick@.service.d directory
  file: path=/etc/systemd/system/wg-quick@.service.d/ state=directory mode=0755

- name: Make sure wg-quick waits for the keys to be generated before starting
  become: true
  ansible.builtin.copy:
    src: 00-wait-for-key-generation.conf
    dest: /etc/systemd/system/wg-quick@.service.d/00-wait-for-key-generation.conf
    owner: root
    group: root
    mode: 0644

- name: Enable the wireguard keygen service
  become: true
  ansible.builtin.systemd:
    name: 'wg0_keys.service'
    enabled: true

- name: Enable the wireguard service
  become: true
  ansible.builtin.systemd:
    name: 'wg-quick@wg0.service'
    enabled: true
