---
- name: Installing ssh
  become: true
  pacman:
    state: present
    name:
      - openssh

- name: Installing sshdgenkeys service
  become: true
  ansible.builtin.copy:
    src: sshdgenkeys.service
    dest: /etc/systemd/system/sshdgenkeys.service
    owner: root
    group: root
    mode: 0644

- name: Enable sshdgenkeys service
  become: true
  ansible.builtin.systemd:
    name: sshdgenkeys
    enabled: yes

- name: Installing sshd service
  become: true
  ansible.builtin.copy:
    src: sshd.service
    dest: /etc/systemd/system/sshd.service
    owner: root
    group: root
    mode: 0644
  notify: 'Restart sshd'

- name: Enable sshd service
  become: true
  ansible.builtin.systemd:
    name: sshd
    enabled: yes

- name: Installing sshd_config
  become: true
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: 'Restart sshd'

- name: Installing ssh nft rule
  become: true
  ansible.builtin.copy:
    src: 10-sshd.nft
    dest: /etc/nftables.d/10-sshd.nft
    owner: root
    group: root
    mode: 0644
  notify: 'Restart nftables'
