---
# currently built/installed by ci-install, until the nftset patch is in a release
# also see: https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q3/015413.html
#
#- name: Installing dnsmasq
#  become: true
#  pacman:
#    state: present
#    name:
#      - dnsmasq

- name: Enable dnsmasq service
  become: true
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes

- name: Disable systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    masked: yes
    enabled: no

- name: Reading mirrorlist
  no_log: true
  ansible.builtin.set_fact:
    mirror_urls: '{{ mirror_urls | default([]) | union([item | regex_search("^Server =.*")]) }}'
  with_lines:
    - cat /etc/pacman.d/mirrorlist
  changed_when: false

- name: Getting mirror domains
  no_log: true
  ansible.builtin.set_fact:
    mirror_domains: '{{ mirror_domains | default([]) | union([item.split("/")[2]]) }}'
  with_items: "{{ mirror_urls }}"
  when: item
  changed_when: false

- name: Installing dnsmasq config
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: true
    mode: 0644
  notify: 'Restart dnsmasq'

- name: Installing dnsmasq nftables rules
  become: true
  ansible.builtin.copy:
    src: 10-dnsmasq.nft
    dest: /etc/nftables.d/10-dnsmasq.nft
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart nftables'

- name: Installing dnsmasq nftables rules (development)
  become: true
  ansible.builtin.copy:
    src: 10-dnsmasq-development.nft
    dest: /etc/nftables.d/10-dnsmasq-development.nft
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart nftables'
  when: development

- name: Installing resolv.conf
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
