---
- name: Installing package
  become: true
  ansible.builtin.package:
    name:
      - dnsmasq

- name: Enable dnsmasq service
  become: true
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true

- name: Disable systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    masked: true

- name: Installing dnsmasq config
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: true
    mode: 0644
  notify: 'Restart dnsmasq'

- name: Installing dnsmasq nftables rules
  become: true
  ansible.builtin.copy:
    src: 10-dnsmasq.nft
    dest: /etc/nftables.d/10-dnsmasq.nft
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart nftables'
