---
- name: Install the seccomp policy for gitlab-runner
  become: true
  ansible.builtin.copy:
    src: gitlab_runner_seccomp.json
    dest: /etc/gitlab-runner-seccomp.json
    owner: root
    group: root
    mode: 0644

- name: gitlab-runner container service
  ansible.builtin.include_role:
    name: "systemd_podman"
  vars:
    container_name: "gitlab-runner"
    container_service_target: infra.target
    container_image: registry.freedesktop.org/mupuf/valve-infra/gitlab-runner:alpine-v13.12.0
    container_env_files:
      - "{{ base_config_env_file }}"
      - "{{ config_env_file }}"
    container_ports:
      - "{{ gitlab_runner_port }}:80/tcp"
    container_volumes:
      - "/mnt:/mnt"
      - "{{ perm_mount }}/gitlab-runner:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/gitlab-runner-seccomp.json:/usr/share/containers/seccomp.json"
    container_depends:
      - executor.service
