---
- name: Installing gitlab runner
  become: true
  pacman:
    state: present
    name:
      - gitlab-runner

- name: Enable gitlab-runner service
  become: true
  ansible.builtin.systemd:
    name: gitlab-runner
    enabled: true

- name: Ensure /etc/systemd/system/gitlab-runner.service.d/ directory exists
  become: true
  ansible.builtin.file:
    mode: 0755
    path: /etc/systemd/system/gitlab-runner.service.d/
    state: directory

- name: Installing gitlab-runner service configuration override
  become: true
  ansible.builtin.template:
    src: 'gitlab-runner.service.d_override.conf.j2'
    dest: '/etc/systemd/system/gitlab-runner.service.d/override.conf'
    mode: 0644
    owner: root
  notify: "Restart gitlab-runner"

- name: Install the prebuild script for gitlab-runner
  become: true
  ansible.builtin.template:
    src: 'gitlab_runner_prebuild.sh.j2'
    dest: '/usr/local/bin/gitlab_runner_prebuild.sh'
    owner: root
    group: root
    mode: 0700
