---
- name: ensure the registry directory exists
  become: true
  ansible.builtin.file:
    mode: 0700
    path: "{{ registry_mount }}"
    state: directory

- name: fdo proxy registry container service
  ansible.builtin.include_role:
    name: "systemd_podman"
  vars:
    container_name: "fdo-proxy-registry"
    container_service_target: infra.target
    container_image: registry.freedesktop.org/mupuf/valve-infra/docker-registry
    container_env:
      - "REGISTRY_PROXY_REMOTEURL=https://registry.freedesktop.org"
    container_env_files:
      - "{{ base_config_env_file }}"
    optional_container_env_files:
      - "{{ config_env_file }}"
    container_ports:
      - "{{ fdo_proxy_registry_port }}:5000/tcp"
    container_volumes:
      - "{{ registry_mount }}:/var/lib/registry"
    service_pre_conditions:
      - "mkdir -pv {{ registry_mount }}"
    part_of:
      - "infra.service"

- name: configuring env
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "{{ base_config_env_file }}"
    mode: '0644'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    block: |
      FDO_PROXY_REGISTRY=ci-gateway:{{ fdo_proxy_registry_port }}
