---
- name: Install the salad server package
  ansible.builtin.pip:
    name: "{{ salad_package_location }}"

- name: Install salad systemd unit file
  ansible.builtin.template:
    src: salad_systemd_unit.j2
    dest: /etc/systemd/system/salad.service
    owner: root
    group: root
    mode: 0644

- name: Enable salad service
  become: true
  ansible.builtin.systemd:
    name: 'salad'
    enabled: true

- name: configuring salad env
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "{{ base_config_env_file }}"
    mode: '0644'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    block: |
      SALAD_PORT={{ salad_port }}
