---
- name: Copy package
  ansible.builtin.copy:
    src: "{{ salad_package_location }}"
    dest: /app/valve-infra/
  register: salad_package

- name: Install salad # noqa no-handler
  ansible.builtin.pip:
    name: "file:///app/valve-infra/salad"
  notify: 'Restart salad'
  # Always install when building the container, since the previous task won't
  # result in a "changed" status.
  # This is necessary because pip installing a local dist is never idempotent,
  # see: https://github.com/pypa/pip/pull/9147
  when: pid_1_name != "systemd" or salad_package.changed

- name: Install salad systemd unit file
  ansible.builtin.template:
    src: salad_systemd_unit.j2
    dest: /etc/systemd/system/salad.service
    owner: root
    group: root
    mode: 0644
  notify: 'Restart salad'

- name: Enable salad service
  become: true
  ansible.builtin.systemd:
    name: 'salad'
    enabled: true

- name: configuring salad env
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "{{ base_config_env_file }}"
    mode: '0644'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    block: |
      SALAD_PORT={{ salad_port }}
  notify: 'Restart salad'
