version: "3.3"

services:
  executor:
    privileged: true
    network_mode: host
    image: registry.freedesktop.org/mupuf/valve-infra/executor
    environment:
      - EXECUTOR_HOST=0.0.0.0
      - EXECUTOR_PORT=80
      - EXECUTOR_REGISTRATION_JOB=/app/job_templates/register.yml.j2
      - EXECUTOR_BOOTLOOP_JOB=/app/job_templates/bootloop.yml.j2
      - SERGENT_HARTMAN_BOOT_COUNT=${SERGENT_HARTMAN_BOOT_COUNT:-100}
      - SERGENT_HARTMAN_QUALIFYING_BOOT_COUNT=${SERGENT_HARTMAN_QUALIFYING_BOOT_COUNT:-100}
      - SERGENT_HARTMAN_REGISTRATION_RETRIAL_DELAY=${SERGENT_HARTMAN_REGISTRATION_RETRIAL_DELAY:-120}
      - GITLAB_REGISTRATION_TOKEN=$GITLAB_REGISTRATION_TOKEN
      - GITLAB_ACCESS_TOKEN=$GITLAB_ACCESS_TOKEN
      - GITLAB_CONF_FILE=/etc/gitlab-runner/config.toml
      - FARM_NAME=$FARM_NAME
      - MARS_URL=http://10.42.0.1:8000
      - SALAD_URL=http://10.42.0.1:8005
      - MINIO_URL=http://10.42.0.1:9000
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
      - FDO_PROXY_REGISTRY=10.42.0.1:8002
      - LOCAL_REGISTRY=10.42.0.1:8004
      - PRIVATE_INTERFACE=$PRIVATE_INTERFACE
      - BOOTS_DEFAULT_KERNEL=http://10.42.0.1:9000/boot/default_kernel
      - BOOTS_DEFAULT_INITRD=http://10.42.0.1:9000/boot/default_boot2container.cpio.xz
      - BOOTS_DEFAULT_CMDLINE=b2c.container="-ti --tls-verify=false docker://10.42.0.1:8002/mupuf/valve-infra/machine_registration:latest register" b2c.ntp_peer="10.42.0.1" b2c.cache_device=none loglevel=6
    volumes:
      - ${PERMANENT_MOUNT}/gitlab-runner:/etc/gitlab-runner
      - ${TMP_MOUNT}/boots:/boots
    restart: unless-stopped
