---
# Not very happy with the local file reference here, it breaks running
# the playbook against a remote system (since the source code is not
# bundled into the production container), which sort of breaks the
# purpose of using Ansible in the first place.
- name: Install the executor server package
  ansible.builtin.pip:
    name: file:///app/valve-infra/executor/server

- name: Install executor systemd unit file
  ansible.builtin.template:
    src: executor_systemd_unit.j2
    dest: /etc/systemd/system/executor.service
    owner: root
    group: root
    mode: 0644

- name: Enable executor service
  become: true
  ansible.builtin.systemd:
    name: 'executor'
    enabled: true

- name: configuring env
  become: true
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: "{{ base_config_env_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    block: |
      PRIVATE_INTERFACE=private
      EXECUTOR_HOST=0.0.0.0
      EXECUTOR_PORT=80
      SERGENT_HARTMAN_BOOT_COUNT={{ sergent_hartman_boot_count }}
      SERGENT_HARTMAN_QUALIFYING_BOOT_COUNT={{ sergent_hartman_qualifying_boot_count }}
      SERGENT_HARTMAN_REGISTRATION_RETRIAL_DELAY={{ sergent_hartman_registration_retrial_delay }}
      GITLAB_CONF_FILE=/mnt/tmp/gitlab-runner/config.toml
      BOOTS_URL=http://{{ private_interface_ip }}:8087
      BOOTS_DEFAULT_KERNEL=http://{{ private_interface_ip }}:{{ minio_port }}/boot/default_kernel
      BOOTS_DEFAULT_INITRD=http://{{ private_interface_ip }}:{{ minio_port }}/boot/default_boot2container.cpio.xz
      BOOTS_DEFAULT_CMDLINE=b2c.container="-ti --tls-verify=false docker://{{ private_interface_ip }}:{{ fdo_proxy_registry_port }}/mupuf/valve-infra/machine_registration:latest register" b2c.ntp_peer="{{ private_interface_ip }}" b2c.cache_device=none loglevel=6
      MARS_DB_FILE=/mnt/permanent/mars_db.yaml
