- hosts: gateway
  vars:
    ansible_connection: local
    tmp_mount: /mnt/tmp
    perm_mount: /mnt/permanent
    prod_env_file: "{{ perm_mount }}/infra.env"
    config_env_file: "{{ perm_mount }}/config.env"
    registry_mount: "{{ tmp_mount }}/registry"

    mars_port: 8000
    gitlab_runner_port: 8001
    fdo_proxy_registry_port: 8002
    local_registry_port: 8004
    salad_port: 8005
    minio_port: 9000

    minio_root_user: minioadmin
    dut_b2c_version: "boot2container_2021_09_09.cpio.xz"
    dut_kernel_version: "default_kernel_2021_09_09"

    sergent_hartman_boot_count: 100
    sergent_hartman_qualifying_boot_count: 100
    sergent_hartman_registration_retrial_delay: 120

    whitelisted_domains:
      # Arch Linux / system admin
      - ntp.org
      - archlinux.thaller.ws
      - alpinelinux.org

      # CI valve-infra
      - debian.org
      - docker.com
      - docker.io
      - freedesktop.org
      - gitlab.freedesktop.org
      - kernel.org
      - minio.io

      # others (cdn, etc)
      - amazonaws.com
      - fastlydns.net
      - files.pythonhosted.org
      - mirror.lty.me
      - packet.net
      - phinau.de
      - pypi.org
      - pythonhosted.org
      - ripe.net
      - steamos.cloud
      - storage.googleapis.com
      - tedata.net

  roles:
    - {role: base,                tags: base}
    - {role: firewall,            tags: firewall}
    - {role: ntpd,                tags: ntpd}
    - {role: sshd,                tags: sshd}
    - {role: dnsmasq,             tags: dnsmasq}
    - {role: dashboard,           tags: dashboard}
    - {role: autologin,           tags: autologin}
    - role: systemd_target
      tags: systemd_target
      vars:
        target_name: infra
        target_description: Valve Infra
        target_after:
          - multi-user.target
        target_wantedby: multi-user.target
    - {role: salad,               tags: salad}
    - {role: minio,               tags: minio}
    - {role: mars,                tags: mars}
    - {role: gitlab_runner,       tags: gitlab_runner}
    - {role: fdo_proxy_registry,  tags: fdo_proxy_registry}
    - {role: local_registry,      tags: local_registry}
    - {role: executor,            tags: executor}
