- hosts: gateway
  vars:
    tmp_mount: /mnt/tmp
    perm_mount: /mnt/permanent
    # env files override in order of entry
    base_config_env_file: "/etc/base_config.env"
    config_env_file: "{{ perm_mount }}/config.env"
    registry_mount: "{{ tmp_mount }}/registry"
    private_interface_ip: "10.42.0.1"

    valve_infra_root: "/app/valve-infra"

    executor_package_location: "{{ valve_infra_root }}/executor/server"
    salad_package_location: "{{ valve_infra_root }}/salad"

    dnsmasq_port: 53
    mars_port: 8000
    gitlab_runner_port: 8001
    fdo_proxy_registry_port: 8002
    local_registry_port: 8004
    salad_port: 8005
    minio_port: 9000
    minio_console_port: 9001

    minio_root_user: minioadmin
    gitlab_access_token: ''
    gitlab_registration_token: ''

    gitlab_runner_user_whitelist:
      - marge-bot
      - chturne
      - mupuf
      - craftyguy
      - tanty
      - bnieuwenhuizen
      - cwabbott0
      - daniel-schuermann
      - flightlessmango
      - JoshuaAshton
      - pendingchaos
      - hakzsam
      - tarceri
      - Venemo
      - neobrain

    gitlab_runner_namespace_whitelist:
      - mesa
      - mupuf
      - tanty
      - chturne
      - flightlessmango
      - gfx-ci
      - drm

    dashboard_monitor_services:
      - executor
      - minio
      - salad
      - gitlab-runner
      - local-registry
      - fdo-proxy-registry

    # Default boot files for DUTs.
    b2c_release: v0.9.5
    kernel_release: v5.16-for-valve-ci
    b2c_url: "https://gitlab.freedesktop.org/mupuf/boot2container/-/releases/{{ b2c_release }}/downloads/initramfs.linux_amd64.cpio.xz"
    kernel_url: "https://gitlab.freedesktop.org/mupuf/valve-infra/-/package_files/117/download"  # v5.16-for-mesa-ci

    sergent_hartman_boot_count: 20
    sergent_hartman_qualifying_boot_count: 19
    sergent_hartman_registration_retrial_delay: 120

    whitelisted_domains:
      # Arch Linux / system admin
      - ntp.org
      - archlinux.thaller.ws
      - alpinelinux.org

      # CI valve-infra
      - debian.org
      - docker.com
      - docker.io
      - freedesktop.org
      - gitlab.freedesktop.org
      - kernel.org
      - minio.io

      # others (cdn, etc)
      - amazonaws.com
      - fastlydns.net
      - files.pythonhosted.org
      - mirror.lty.me
      - packet.net
      - phinau.de
      - pypi.org
      - pythonhosted.org
      - ripe.net
      - steamos.cloud
      - storage.googleapis.com
      - tedata.net

    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLImGjZQTo61R6+M8as3SNqXpQF/W0WFsKa95LDs3hxp7sXdkXhvU3/9BeGTP+QBuCAb1DE2F2h78Q2d2cIfaJZCjEiszYaEWfh8G/4o6tNULk3xJQ5uzjXe1orlxLTZeHbw3wP46woR+gWujZy3DmJtmqiFDwNfHhn0+ZDYgIo8J5EfIGIAqHfbp6xMoH/0faWzsPvQnZw6qxRmSppHMgAyNQW/Ba7pEWkcNCb2k4tLlHExbXb30neLQm0Nxxkx9+zKUdo+TL+T5kLbWUnXI7flCBkz7Nz9NwURxVLxlMgTrjRzGZ57ieOyYG4/MssHaRCZlJZKPnq5se+BrZWctYFhRUjydl2mvKPaZMNbWuzieT3BIysbHTNZ2m9NpKg5a3PRKQveBpfjbb3FxBPY5J4cmUmONgb082WtVe1yWtS+clh6rnyqDr3S0IHnCQAP9+fBjG3VHs4BPvPl3uIhI3lEDCoeQhQmXu78AdbOfa62ngLovmA/r1HuF9yb1XgfWkBYQIBeykJXJsCm/ofusLHYAzWt+puxZl9wcdcrlKNwUfrKDuM3SZ50PmfIawFSpqQ9Q1JOjJ8Yt4BRb+1TRao1EfwAjSQqA5EUFCiLh99Yzj1k9ME+bYk0WMcPyRZKX8il/5B9giX8mF59EpiD5No+bLdX3g+aqQosj3foYvbQ== mupuf@mupufTmi"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGYQSlLPQzKlT45aoO5hZX7v1TYFcilXE4FTeFCEImPy clayton@igalia.com"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtOV9ebXq4JnCiloBDNEUolJuZrkNLL8XEDleb+z70ureQADhbones/AdRZUCzuFtUjCp1VtBkhak78CFiBKo74Evxhugl0PTKsFk9i7Ofsb6b/1As4pT7AK8BR5t+cGODhTkTAwCOU1AKm9J9MjE48dCOcLY1geXOTo33xdTLuHh40KZvIXSTQAHa3zbjMXls+tGLRAIIYhL1UbAm65/WyzphAXVoJKp4qDK8QnLzWMPAvnaVWNXoeV2AoQa+e9GodImeaaPIIiZcrg7NeihAul0h++gXZ/db2Gf0RIvOT49K/bbqF2aOfT7Z4zFjEUtMYZ6EjGqVC6MQdk+nw2ari889RHfaBP5AL/S0SuoWoXzi2LFSHNYPUsLG7TnzLZ7zTG/l4S1UVUrg+2y86rVZf+obliURdRfDBIkqaifjL4xOZP2vf+x9CZkoC6PGlQKupLloP8KHZvx87YiNNc14LtmRtm5wapacFh6NqFRAhyfk3cqBwEEhvTbkwftps5TkDAsvLc1beBsR/EVO2WC/NpI2lQrOjGqEF9JUix7hfXj+IB/TYTRD5Pwp8tAkojeqeZSWSqwgH2cHbBLLJEixt6O6BNmRVjlvuROv1y965dJULQYkBGSr3v+6F1P/LjDbahtcVOrMF23j6oFFgKK6A5/sEsT5LgS+kRI0nqKFHw== cturner@igalia.com"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDstcXqWJGzpy0kTEB3rf5LNfLCfeqjwyh06bHO5LBBw05TNSJomBQjvBJzVKbT9QB9x8MfVf+Z/MrFo37NkdoOK/w7tb/1PGaGIVp6FOOyjznO87sLniVxzcJLOgPTA6iejfnXpAS3iUgKxyxouMykeWuGh5KRW/bT+HL+bPZPhk/fXskynCdEH0J6ZDI3+F5kPHVEbdSDeT+BvwJsbyHtdDsDigP/vGJyPn5uEpkCEkScsIqy5/GdXsgyTW9jX6gziZZFW4r5MQlKUX0ALvEGoh5n4rl491QoxOEJxLMcEmfyR3d+TN4XBG1pW/s5qoFXBmDABYrMZh1lk2RRlrnJ pabelenda@ideafix"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHOZAQx1PVe60GBLRYh6V7KdH5l5lsQkFWNQoM7t+UyGDd+YnpBJ66vLAE8Omqh4kk1eZlZDE7EV2ID5YXNWiMqojhq3UDmZ/Syvea/4wP3W33smQur2uR826VAt/F5ePWtRMr9VegTZwiHEzmCDXp9DhwRek58L3Quju3u9Z/kDNoKAJ3197dGtti6icv4zBKYSK+lxrMy2oH4gfJtljpW5JTVsSYvuGRYesQQKpNl6gULfeL3Vh0DkaGhNkf8e7mdXmgAMbMW61P5oMFJXoNt6NJBRq3BbaQ4R/0L3SHgqnaT58LR5a+fRXimcomMD3g8GhSpYY2b+3iUhskrdbh pabelenda@maestria"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDmwHU7L+WMxLCTh6oOwCBQ+TKynq7OPCgAu4+ikulVcddXhCEoryfROO0EeTT2z5tEMhzE7VnqISc5kakOOprvh5aoGDmsX7noS8hHdMV8G651GUX7LNI0J2VgjztGl8IBRK2oH1zPKZ9no7nBBuA7Ia4itUryz/fGQO8Bog6Afni/V7u6C4UsPHf1sDNXOaGfLBIuC1zR5XMAYb/lr4mUOd1CmepmLCzn5XnPyElTX3OWLrhO+4ltnpK8AhGDPZ10siJNKztyhN5brMqLBALH2dr5H/rEyKjEp8YJ7bvpRrokfqO0Zbnl7f0IBaqkxugk3uWGC1LAwZUt2PaibKEFFfb0L8Zfdx7/xSKm+V187OJbPCW91pHP7R5+CYK/MzAvTPiB1hIDjqeY4l0qBeqUlP30WYNCfN6pGLp7CVOFILq/1zhQVlhfTKgTL/pUPVg0r/94T7JRThZsy3OGI/+/PszliC0+2IrPvmXY54/viwEh6/Oo0GmTw0Oa9orDBykw6+lNCkWf8zLrVIidxf5InSY6LeCOs8e2Eow4tticPPiiGQWK6JPuJR3qOFWtHoluSXtnb59JXvKGwf+9wa3t7+aSoc4kwTM2jPwGd7F8PcZ1+Be+I3BuA9YodB2zg96+UzI+sB1NXjOM9veyonwZ6iIz+fiFXAGcOT6G9yOMBQ== tanty@valve-infra-gateway"

  roles:
    # the 'always' tag is used for roles that must always run, i.e. other roles
    # depend on them but we don't want to set "dependencies:" for every role
    # that does
    - {role: pid1,                tags: always}

    - {role: base,                tags: base}
    - {role: containers,          tags: containers}
    - {role: network_setup,       tags: network_setup}
    - {role: firewall,            tags: firewall}
    - {role: wireguard,           tags: wireguard}
    - {role: ntpd,                tags: ntpd}
    - {role: sshd,                tags: sshd}
#    - {role: dnsmasq,             tags: dnsmasq}
    - {role: dashboard,           tags: dashboard}
    - {role: autologin,           tags: autologin}
    - {role: salad,               tags: salad}
    - {role: minio,               tags: minio}
    - {role: gitlab_runner,       tags: gitlab_runner}
    - {role: fdo_proxy_registry,  tags: fdo_proxy_registry}
    - {role: local_registry,      tags: local_registry}
    - {role: executor,            tags: executor}
    - {role: infra,               tags: infra}
