- hosts: gateway
  vars:
    ansible_connection: local
    tmp_mount: /mnt/tmp
    perm_mount: /mnt/permanent
    prod_env_file: "{{ perm_mount }}/infra.env"
    config_env_file: "{{ perm_mount }}/config.env"

  roles:
    - base
    - firewall
