---
- name: Installing minio
  become: true
  pacman:
    state: present
    name:
      - minio

- name: configuring minio env
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "{{ base_config_env_file }}"
    mode: '0644'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ role_name }}"
    block: |
      MINIO_ROOT_USER=minioadmin
      VALVETRACES_MINIO_PASSWORD={{ valvetraces_minio_password }}
  # config changes are applied to minio by this service
  notify: "Restart minio_configure"

- name: Adding minio firewall config
  become: true
  ansible.builtin.template:
    src: 'minio.nft.j2'
    dest: /etc/nftables.d/50-minio.nft
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart nftables'

- name: Installing minio_configure script
  become: true
  ansible.builtin.template:
    src: 'minio_configure.sh.j2'
    dest: '/usr/local/bin/minio_configure'
    mode: 0755
    owner: root
  # config changes are applied to minio by this service
  notify: "Restart minio_configure"

- name: Installing minio_configure systemd.service file
  become: true
  ansible.builtin.template:
    src: 'minio_configure.service.j2'
    dest: '/etc/systemd/system/minio_configure.service'
    mode: 0644

- name: Ensure minio configuration directory exists
  become: true
  ansible.builtin.file:
    mode: 0744
    path: /etc/minio
    state: directory

- name: Installing minio bucket policies
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: 'valvetraces.json.j2', dest: '/etc/minio/valvetraces.json' }
    - { src: 'valvetraces-ro.json.j2', dest: '/etc/minio/valvetraces-ro.json' }

- name: Ensure /etc/systemd/system/minio.service.d/ directory exists
  become: true
  ansible.builtin.file:
    mode: 0755
    path: /etc/systemd/system/minio.service.d/
    state: directory

- name: Installing minio service configuration override
  become: true
  ansible.builtin.template:
    src: 'minio.service.d_override.conf.j2'
    dest: '/etc/systemd/system/minio.service.d/override.conf'
    mode: 0644
    owner: root
  notify: "Restart minio"

- name: Enable minio_configure service
  become: true
  ansible.builtin.systemd:
    name: 'minio_configure'
    enabled: true

- name: Installing minio_genpw script
  become: true
  ansible.builtin.template:
    src: 'minio_genpw.sh.j2'
    dest: '/usr/local/bin/minio_genpw'
    mode: 0755
    owner: root

- name: Installing minio_genpw systemd.service file
  become: true
  ansible.builtin.template:
    src: 'minio_genpw.service.j2'
    dest: '/etc/systemd/system/minio_genpw.service'
    mode: 0644

- name: Enable minio_genpw service
  become: true
  ansible.builtin.systemd:
    name: 'minio_genpw'
    enabled: true
